services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1-python3.9
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/airflow/include:/opt/airflow/dags
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./entrypoint.sh:/entrypoint.sh
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: bash /entrypoint.sh

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    environment:
      PGADMIN_LISTEN_PORT: 80  
    ports:
      - "5050:80"
    depends_on:
      -  db
    volumes:
      - pgadmin_data:/var/lib/pgadmin   
    restart: unless-stopped

  streamlit:
    build: ./dashboards/streamlit_app
    depends_on:
      - db
    volumes:
      - ./dashboards/streamlit_app:/streamlit_app
    ports:
      - "8501:8501"

volumes:
  pg_data:
  pgadmin_data:  
    