services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1-python3.9
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/airflow/include:/opt/airflow/dags  
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./entrypoint.sh:/entrypoint.sh
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: bash /entrypoint.sh

volumes:
  pg_data:    
    